<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "h2dmailsub"
 *
 * Auto generated by Extension Builder 2016-02-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Direct Mail Subscription',
	'description' => 'Direct Mail Subscription based on ExtBase and Fluid',
	'category' => 'plugin',
	'author' => 'HOCHZWEI',
	'author_email' => 'typo3@hoch2.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'tt_address' => '3.0.0-0.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);